### ISSUE TITLE
fix failing container build

### ISSUE THREAD

**Issue by martenson** [RECETOX/Retip#1]
The build fails on dockerhub, [log](https://hub.docker.com/repository/registry-1.docker.io/recetox/retip/builds/9b776f28-35d1-4192-9a43-1f6838cbbcce).

**Comment by smartx-usman** [comment]
I think docker image required to build needs a lot of memory that is unavailable when using shared resources. As a workaround, local build and push of docker image to DockerHub is applied successfully.

**Comment by martenson** [comment]
Thanks @smartx-usman !
